# Generated by Django 5.2.12 on 2026-09-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
