# Generated by Django 5.2.16 on 2026-07-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
